package paycard

// PDOLTagInfo stores the information related to an EMV tag
type PDOLTagInfo struct {
	Definition  string
	Description string
}

// EmvPDOLTags is a map of common EMV tags used in PDOL with their definitions and descriptions
var EmvPDOLTags = map[string]PDOLTagInfo{
	"9F66": {Definition: "Terminal Transaction Qualifiers (TTQ)", Description: "Indicates terminal capabilities and transaction requirements."},
	"9F02": {Definition: "Authorized Amount", Description: "The amount of the transaction in the minor currency unit (e.g., cents)."},
	"9F03": {Definition: "Secondary Amount", Description: "The cashback amount, if applicable, in the minor currency unit."},
	"9F1A": {Definition: "Terminal Country Code", Description: "A two-byte code representing the country of the terminal in numeric ISO format."},
	"95":   {Definition: "Terminal Verification Results (TVR)", Description: "A five-byte code summarizing the result of the terminal's risk management checks."},
	"5F2A": {Definition: "Transaction Currency Code", Description: "A two-byte code representing the currency of the transaction, in ISO numeric format."},
	"9A":   {Definition: "Transaction Date", Description: "The date of the transaction in YYMMDD format."},
	"9C":   {Definition: "Transaction Type", Description: "Indicates the type of transaction, e.g., purchase, cash advance, etc."},
	"9F37": {Definition: "Unpredictable Number", Description: "A four-byte random number generated by the terminal for transaction uniqueness."},
	"9F21": {Definition: "Transaction Time", Description: "The time of the transaction in HHMMSS format."},
	"9F35": {Definition: "Terminal Type", Description: "Indicates the type of terminal, e.g., unattended POS, ATM, etc."},
	"9F7C": {Definition: "Merchant Custom Data", Description: "Additional data from the merchant, used in some specific implementations."},
	"9F4E": {Definition: "Merchant Name and Location", Description: "The name and location of the merchant."},
	"9F5A": {Definition: "Terminal Transaction Information", Description: "Terminal-specific data, mainly related to EMVCo contactless payments."},
	"9F6E": {Definition: "Form Factor Indicator (FFI)", Description: "Indicates the form factor of the terminal device (contactless, etc.)."},
	"9F33": {Definition: "Terminal Capabilities", Description: "Indicates the capabilities of the terminal, such as offline data authentication support."},
	"9F40": {Definition: "Additional Terminal Capabilities", Description: "Provides more detailed information about the terminal’s capabilities."},
	"DF61": {Definition: "Application Preferred Name", Description: "Terminal-preferred application name, used in some implementations."},
	"DF62": {Definition: "Issuer Preferred Name", Description: "Issuer-preferred application name."},
	"9F09": {Definition: "Application Version Number", Description: "Indicates the version of the EMV application on the card."},
	"9F7B": {Definition: "Electronic Cash Balance", Description: "Balance available for electronic cash transactions, used mainly in stored-value cards."},
	"9F6D": {Definition: "Card Program Identifier", Description: "Identifies the specific program for the EMV card, relevant to specific implementations."},
	"9F34": {Definition: "Cardholder Verification Method (CVM) Results", Description: "Describes the result of the CVM processing."},
	"9F1B": {Definition: "Terminal Floor Limit", Description: "The maximum amount allowed for offline transactions."},
	"9F1C": {Definition: "Terminal Identification", Description: "A unique identifier for the terminal, typically set by the acquirer."},
	"9F15": {Definition: "Merchant Category Code", Description: "Indicates the type of merchant, such as grocery, fuel, or retail."},
	"9F16": {Definition: "Merchant Identifier", Description: "A unique identifier for the merchant."},
}

// GetPDOLTagInfo provides information about an EMV tag if it exists in the map
func GetPDOLTagInfo(tag string) (PDOLTagInfo, bool) {
	info, exists := EmvPDOLTags[tag]
	return info, exists
}
