merchant_id: "ac92d523-7ec3-4353-b504-66b19073be4d"
# acquirer_url: "http://127.0.0.1:8080"
acquirer_url: "https://ftdc-acquirer.ngrok.io"
default_amount: 0
kernel: ftdc # ftdc or universal
printer_url: https://ftdc-printer.ngrok.io
# for local testing, you can use:
# printer_url: http://127.0.0.1:8085
